monsters_storage_large = [
    "Acidic Glavenus",
    "Ancient Leshen",
    "Anjanath",
    "Azure Rathalos",
    "Banbaro",
    "Barioth",
    "Bazelgeuse",
    "Beotodus",
    "Black Diablos",
    "Brachydios",
    "Brute Tigrex",
    "Coral Pukei-Pukei",
    "Deviljho",
    "Diablos",
    "Dodogama",
    "Ebony Odogaron",
    "Fulgur Anjanath",
    "Furious Rajang",
    "Glavenus",
    "Gold Rathian",
    "Great Girros",
    "Great Jagras",
    "Jyuratodus",
    "Kulu-Ya-Ku",
    "Nightshade Paolumu",
    "Odogaron",
    "Paolumu",
    "Pink Rathian",
    "Pukei-Pukei",
    "Radobaan",
    "Raging Brachydios",
    "Rajang",
    "Rathalos",
    "Rathian",
    "Savage Deviljho",
    "Scarred Yian Garuga",
    "Seething Bazelgeuse",
    "Shrieking Legiana",
    "Silver Rathalos",
    "Stygian Zinogre",
    "Tigrex",
    "Tobi-Kadachi",
    "Tzitzi-Ya-Ku",
    "Uragaan",
    "Viper Tobi-Kadachi",
    "Yian Garuga",
    "Zinogre"
]

monsters_storage_elder = [
    "Behemoth",
    "Kirin",
    "Kulve Taroth",
    "Kushala Daora",
    "Lunastra",
    "Nergigante",
    "Teostra",
    "Vaal Hazak",
    "Xeno'jiiva",
    "Zorah Magdaros",
    "Namielle",
    "Ruiner Nergigante",
    "Safi'jiiva",
    "Shara Ishvalda",
    "Blackveil Vaal Hazak",
    "Velkhana"
]

monsters_storage_small = [
    "Anteka",
    "Apceros",
    "Aptonoth",
    "Barnos",
    "Boaboa",
    "Cortos",
    "Gajalaka",
    "Gajau",
    "Gastodon",
    "Girros",
    "Grimalkyne",
    "Hornetaur",
    "Jagras",
    "Kelbi",
    "Kestodon",
    "Mernos",
    "Mosswine",
    "Noios",
    "Popo",
    "Raphinos",
    "Shamos",
    "Vespoid",
    "Wulg"
]

monsters_storage_endemic = [
    "Shepherd Hare",
    "Pilot Hare",
    "Forest Gekko",
    "Wildspire Gekko",
    "Gloom Gekko",
    "Moonlight Gekko",
    "Vaporonid",
    "Scavantula",
    "Revolture",
    "Blissbill",
    "Dung Beetle",
    "Bomb Beetle",
    "Paratoad",
    "Sleeptoad",
    "Nitrotoad",
    "Wiggler",
    "Wiggler Queen",
    "Carrier Ant",
    "Emperor Hopper",
    "Tyrant Hopper",
    "Iron Helmcrab",
    "Soldier Helmcrab",
    "Emerald Helmcrab",
    "Stonebill",
    "Rime Beetle",
    "Pearlspring Macaqu",
    "Goldspring Macaque",
    "Crowned Prawn",
    "Duffel Penguin",
    "Arrowhead Gekko",
    "Moly",
    "Mossy Moly",
    "Rocky Moly",
    "Fluffy Moly",
    "Spiny Moly",
    "Glacial Moly",
    "Rowdy Moly",
    "Climbing Joyperch"
    "Pink Parexus",
    "Burst Arowana",
    "Bomb Arowana",
    "Andangler",
    "Hopguppy",
    "Petricanths",
    "Whetfish",
    "Gastronome Tuna",
    "King Marlin",
    "Goldenfish",
    "Platinumfish",
    "Goldenfry",
    "Sushifish",
    "Gunpowderfish",
    "Glass Parexus",
    "Sealord's Crestfish",
    "Downy Crake",
    "Bristly Crake",
    "Wintermoon Nettle",
    "Cactuar",
    "Cactuar Cutting",
    "Flowering Cactuar Cutting",
    "Cobalt Flutterfly",
    "Phantom Flutterfly",
    "Omenfly",
    "Augurfly",
    "Scalebat",
    "Elegant Coralbird",
    "Dapper Coralbird",
    "Vigorwasp",
    "Giant Vigorwasp",
    "Flying Meduso",
    "Flashfly",
    "Grandfather Mantagrell",
    "Moon Slug",
    "Woodland Pteryx",
    "Forest Pteryx",
    "Hercudrome",
    "Gold Hercudrome",
    "Prism Hercudrome",
    "Blue Diva",
    "Copper Calappa",
    "Gold Calappa",
    "Gold Helmcrab",
    "Shiny Gold Helmcrab",
    "Gold Scalebat",
    "Tsuchinoko",
    "Nekker"
]
